blog:
    resource: "@BlogBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

default:
    path: /homepage
    defaults:
      _controller: AppBundle:Default:index

current-time:
    path: /current-time
    defaults:
      _controller: AppBundle:Time:currentTime

square:
    path: /square/{number}
    defaults:
      _controller: AppBundle:Time:square